<div class="footer-section">
  <div class="container">
    <div class="footer-left">
      <p>Copyright &copy; 2017. 版本所有 by 星凯智翎教育科技有限公司
      </p>
    </div>
    <div class="bottom-menu">
      <ul>
        <li><a href="index.html" class="active">主页</a></li>
        <li><a href="blog.html">咨询专家</a></li>
        <li><a href="pages.html">page</a></li>
        <li><a href="features.html">成功案例</a></li>
        <li><a href="contact.html">联系我们</a></li>
      </ul>
    </div>
    <div class="clearfix"></div>
    <script type="text/javascript">
      $(document).ready(function () {
        /*
         var defaults = {
         containerID: 'toTop', // fading element id
         containerHoverID: 'toTopHover', // fading element hover id
         scrollSpeed: 1200,
         easingType: 'linear'
         };
         */

        $().UItoTop({easingType: 'easeOutQuart'});

      });
    </script>
    <a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
  </div>
</div>