<!DOCTYPE HTML>
<html>
<head>
    <title>Home</title>
    <link href="/asset/frontend/css/bootstrap.css" rel="stylesheet" type="text/css" media="all">
    <link href="/asset/frontend/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="kaixiang,凯翔教育,education" />
    <script type="application/x-javascript"> addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);
        function hideURLbar() {
            window.scrollTo(0, 1);
        } </script>
    <link
        href='http://fonts.useso.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic'
        rel='stylesheet' type='text/css'>
    <link href='http://fonts.useso.com/css?family=Fugaz+One' rel='stylesheet' type='text/css'>
    <script src="/asset/frontend/js/jquery-1.11.1.min.js"></script>
    <script src="/asset/frontend/js/responsiveslides.min.js"></script>
    <script>
        $(function () {
            $("#slider").responsiveSlides({
                auto: true,
                nav: true,
                speed: 500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>
    <!---- start-smoth-scrolling---->
    <script type="text/javascript" src="/asset/frontend/js/move-top.js"></script>
    <script type="text/javascript" src="/asset/frontend/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1200);
            });
        });
    </script>
    <!---End-smoth-scrolling---->
    <script src="/asset/frontend/js/bootstrap.js"></script>

</head>
<body>
<!-- header -->
<div class="header" id="home">

    <div class="header-top">
        <div class="container">
            <div class="icon">
                <ul>
                    <li><i class="message"></i></li>
                    <li><a href="mailto:example@mail.com">kaixiang@kx.com</a></li>
                    <li><i class="phone"></i></li>
                    <li><p>+00(123)1234567</p></li>
                </ul>
            </div>
            <div class="social-icons">
                <a href="#"><i class="icon1"></i></a>
                <a href="#"><i class="icon2"></i></a>
                <a href="#"><i class="icon3"></i></a>
                <a href="#"><i class="icon4"></i></a>
                <a href="#"><i class="icon5"></i></a>
                <a href="#"><i class="icon6"></i></a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="container">
        <div class="header-bottom">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-brand">
                            <h1><a href="http://kaixiang.crazylaw.cn">凯翔教育</a></h1>
                        </div>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="http://kaixiang.crazylaw.cn">主页 <span class="sr-only">(current)</span></a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true"
                                   aria-expanded="false">选择<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="http://kaixiang.crazylaw.cn/school/index/search">院校搜索</a></li>
                                    <li><a href="http://kaixiang.crazylaw.cn/school/index/rank">院校排名</a></li>
                                    <li><a href="#">留学申请指南</a></li>
                                </ul>
                            </li>
                            <li><a href="http://kaixiang.crazylaw.cn/Profession/index/index">咨询专家</a></li>
                            <li><a href="#">pages</a></li>
                            <li><a href="#">成功案例</a></li>
                            <li><a href="http://kaixiang.crazylaw.cn/apply/index/index">留学申请</a></li>
                        </ul>

                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>

        </div>
    </div>
</div>