<?
// layout header 头部
include_once dirname(__FILE__, 2) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'header_layout.phtml';
?>

<!-- header-section-ends -->
<div class="header-slider">
  <div class="slider">
    <div class="callbacks_container">
      <ul class="rslides" id="slider">
        <li>
          <img src="/asset/frontend/images/banner.jpg" alt="">
          <div class="caption">
            <h3>留学申请 专业机构</h3>
            <p>在选择请中介进行留学资讯服务的消费者当中，对中介服务不满意的人数竟达到35.71%，整体满意度不尽人意。
              同时，从全国消协组织受理留学相关投诉情况了解到，2014年全年对留学中介的投诉量为73起，而2015年仅上半年投诉量就上升到117起，
              投诉量显著上升。.</p>
          </div>
        </li>
        <li>
          <img src="/asset/frontend/images/banner1.jpg" alt="">
          <div class="caption">
            <h3>困惑不知道如何选择？</h3>
            <p>在选择请中介进行留学资讯服务的消费者当中，对中介服务不满意的人数竟达到35.71%，整体满意度不尽人意。
              同时，从全国消协组织受理留学相关投诉情况了解到，2014年全年对留学中介的投诉量为73起，而2015年仅上半年投诉量就上升到117起，
              投诉量显著上升。.</p>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
</div>
<div class="beautifull">
  <div class="container">
    <div class="beautifull-header">
      <h4>星凯智翎教育科技有限公司</h4>
      <p>星凯智翎教育科技有限公司是集教育服务、教育咨询、网络服务与教育培训为一体的综合性教育服务机构，
        目前中国专注于留学服务特别是留学咨询服务与留学考试服务的新兴公司。公司总部位于广州，成立于2016年，
        注册资金5000万，拥有十年从业经验的金牌留学顾问，一家大学生创业公司。
      </p>
    </div>
    <div class="beautifull-grids">
      <div class="col-md-4 beautiful-grid">
        <div class="icon1">
          <i class="heart"></i>
        </div>
        <div class="passion">
          <h4>公司主要业务</h4>
          <p>办理自费出国留学、境内外学历学位认证、高层次留学人才界定、办理外国专家证、办理人事关系调动手续或聘（录）用手续、
            博士后进出站手续、落户、居住证、高新技术企业认定、申办税务登记、营业执照、办理因公（私）出国护照和港澳台通行证、
            办理多次因公（私）出入境或赴港澳台签证、子女入学、配偶就业、人事代理、劳动事务代理、办理社保、办理特殊医保服务、
            人才引进等23项服务。
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="col-md-4 beautiful-grid">
        <div class="icon1">
          <i class="lamp"></i>
        </div>
        <div class="passion">
          <h4>发展现状</h4>
          <p>随着出国留学人数持续增长，学生和家长对留学中介机构的实际需求也在增长。
            虽然留学信息日趋透明，但由于欧美院校申请标准的多元化以及语言障碍，导致多数人DIY申请会遇到很多困难。
            加上生活水平的提高，一部分有能力自己申请的人也更愿意通过“花钱买服务”的方式节约申请过程中的时间和精力。
            根据中国教育国际交流协会自费出国留学中介服务分会结果显示，
            84.85%的用户在留学申请时选择了留学中介机构进行服务。
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="col-md-4 beautiful-grid">
        <div class="icon1">
          <i class="star"></i>
        </div>
        <div class="passion">
          <h4>公司优势</h4>
          <p>凯翎与广州第一家留学机构广东省留学人员服务中心达成合作意见，拥有近30年的留学申请经验，
            掌握了全球Top50顶尖院校所有专业及其教授不间断的招生情报，依托可靠的数据分析为客户提供精准无误的申请战略。
            目前广东省留学人员服务中心校友网络已遍及全球各顶尖名校，珍贵的人脉关系为学子的申请增加了更多保障。
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<div class="checkout-section">
  <div class="container">
    <div class="checkout-header">
      <h4>会场展示</h4>
      <p>我们拥有出色的团队成员和会所给你提供优质的服务和体验</p>
    </div>
    <div id="portfoliolist">
      <div class="portfolio">
        <div class="portfolio-wrapper">
          <a href="#small-dialog" class="b-link-stripe b-animate-go  thickbox play-icon popup-with-zoom-anim">
            <img class="work-img" src="/asset/frontend/images/img1.jpg" alt=""/>
            <div class="b-wrapper"><h2 class="b-animate b-from-left    b-delay03 "><img
                  src="/asset/frontend/images/icon-eye.png" alt=""/></h2>
            </div>
          </a>
        </div>
        <div class="bottom-header">
          <h5>会场当天申请讲解</h5>
          <p>专业人士讲解</p>
        </div>
      </div>
      <div class="portfolio">
        <div class="portfolio-wrapper">
          <a href="#small-dialog1" class="b-link-stripe b-animate-go  thickbox play-icon popup-with-zoom-anim">
            <img class="work-img" src="/asset/frontend/images/img2.jpg" alt=""/>
            <div class="b-wrapper"><h2 class="b-animate b-from-left    b-delay03 "><img
                  src="/asset/frontend/images/icon-eye.png" alt=""/></h2>
            </div>
          </a>
        </div>
        <div class="bottom-header">
          <h5>工作人员耐心与客户沟通</h5>
          <p>客户至上</p>
        </div>
      </div>

      <div class="clearfix"></div>
    </div>
    <link href="/asset/frontend/css/popuo-box.css" rel="stylesheet" type="text/css" media="all"/>
    <script src="/asset/frontend/js/jquery.magnific-popup.js" type="text/javascript"></script>
    <!-- //pop-up-box -->
    <div id="small-dialog" class="mfp-hide">
      <div class="image-top">
        <img src="/asset/frontend/images/img1.jpg" alt=""/>
        <p>我们将全程为你提供优质的服务。</p>
      </div>
    </div>
    <div id="small-dialog1" class="mfp-hide">
      <div class="image-top">
        <img src="/asset/frontend/images/img2.jpg" alt=""/>
        <p>我们将全程为你提供优质的服务。</p>
      </div>
    </div>

    <script>
      $(document).ready(function () {
        $('.popup-with-zoom-anim').magnificPopup({
          type: 'inline',
          fixedContentPos: false,
          fixedBgPos: true,
          overflowY: 'auto',
          closeBtnInside: true,
          preloader: false,
          midClick: true,
          removalDelay: 300,
          mainClass: 'my-mfp-zoom-in'
        });
      });
    </script>
    <!-- Work Ends Here -->


    <div class="screen-shots">
      <!--sreen-gallery-cursual-->
      <div class="sreen-gallery-cursual">
        <!-- start content_slider -->
        <div id="owl-demo" class="owl-carousel">
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic3.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic4.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic5.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic6.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic3.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic4.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic5.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic6.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic3.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic4.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic5.jpg"/>
              </div>
            </div>
          </div>
          <div class="item">
            <div class="item-grid">
              <div class="item-pic">
                <img src="/asset/frontend/images/pic6.jpg"/>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--//sreen-gallery-cursual-->
    </div>
    <!-- requried-jsfiles-for owl -->
    <link href="/asset/frontend/css/owl.carousel.css" rel="stylesheet">
    <script src="/asset/frontend/js/owl.carousel.js"></script>
    <script>
      $(document).ready(function () {
        $("#owl-demo").owlCarousel({
          items: 4,
          lazyLoad: true,
          autoPlay: true,
          navigation: false,
          navigationText: false,
          pagination: true,
        });
      });
    </script>
    <!-- //requried-jsfiles-for owl -->

  </div>
</div>
<div class="wantto-section">
  <div class="container">
    <h4>想要向我们申请?</h4>
    <p>请点击联系我们。心动不如行动！</p>
    <a href="#" class="hvr-rectangle-in">申请</a>
  </div>
</div>
<div class="contact-section">
  <div class="container">
    <div class="contact-grids">
      <div class="col-md-3 contact-grid">
        <h5>who we are</h5>
        <p>星凯智翎教育科技有限公司是集教育服务、教育咨询、网络服务与教育培训为一体的综合性教育服务机构，
          目前中国专注于留学服务特别是留学咨询服务与留学考试服务的新兴公司。</p>
        <a href="#" class="more">更多 关于我们<img src="/asset/frontend/images/arrow.png"></a>
      </div>
      <div class="col-md-3 contact-grid">
        <h5>联系我们</h5>
        <p>公司总部位于广州，成立于2016年， 注册资金5000万，拥有十年从业经验的金牌留学顾问，一家大学生创业公司。</p>
        <div class="icon2">
          <ul>
            <li><i class="indicate"></i></li>
            <li><p class="label1">天河北 124号, 广州, 经纬度：123 666</p></li>
          </ul>
          <ul>
            <li><i class="phone"></i></li>
            <li><p class="label1">+(020)8608754</p></li>
          </ul>
          <ul>
            <li><i class="message"></i></li>
            <li><a href="mailto:example@mail.com">kaixiang@kx.com</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 contact-grid">
        <h5>会场展示</h5>
        <div class="cont">
          <div class="contact-leftgrid">
            <div class="img-grid1">
              <img src="/asset/frontend/images/pic7.jpg">
            </div>
            <div class="img-grid2">
              <img src="/asset/frontend/images/pic8.jpg">
            </div>
            <div class="clearfix"></div>
          </div>

          <div class="contact-rightgrid">
            <div class="img-grid3">
              <img src="/asset/frontend/images/pic9.jpg">
            </div>
            <div class="img-grid4">
              <img src="/asset/frontend/images/pic10.jpg">
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
      <div class="col-md-3 contact-grid">
        <h5>您的联系邮箱</h5>
        <p>请输入您的联系邮箱，我们将会回访你的邮箱，把更加详情的资料与你分享，我们期待您和我们的沟通和联系！</p>
        <div class="subscribe">
          <form>
            <input type="text" class="text" value="Your email..." onFocus="this.value = '';"
                   onBlur="if (this.value == '') {this.value = ' Enter your email';}">
            <input type="submit" value="Send">
          </form>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<?
// layout footer 脚部
include_once dirname(__FILE__, 2) . DIRECTORY_SEPARATOR . 'layout' . DIRECTORY_SEPARATOR . 'footer_layout.phtml';
?>
</body>
</html>